name: Publish to Foundry VTT

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Update Version, URL, Manifest, Download Links in module.json
      id: sub_manifest_link_version
      uses: microsoft/variable-substitution@v1
      with:
        files: 'module.json'
      env:
        version: ${{github.event.release.tag_name}}
        url: https://github.com/${{github.repository}}
        manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
        download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip

    - name: Zip Module Files
      id: zip_files
      run: zip -r ./module.zip lang/ scripts/ styles/ templates/ LICENSE.txt module.json

    - name: Update Release with module.json and module.zip
      id: create_version_release
      uses: ncipollo/release-action@v1.16.0
      with:
        allowUpdates: true # Set this to false if you want to prevent updating existing releases
        omitNameDuringUpdate: true
        omitBodyDuringUpdate: true
        omitDraftDuringUpdate: true
        omitPrereleaseDuringUpdate: true
        token: ${{ secrets.RELEASE_TOKEN }}
        artifacts: './module.json, ./module.zip'

    - name: Publish Module to FoundryVTT Website
      id: publish_to_foundry_website
      if: ${{ !github.event.release.unpublished && !github.event.release.prerelease }}
      uses: cs96and/FoundryVTT-release-package@v1.0.2
      with:
        package-token: ${{ secrets.FOUNDRY_PACKAGE_TOKEN }}
        manifest-url: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.json
        notes-url: https://github.com/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }}
